### ISSUE TITLE
Set the chats in the chat box as attributes to the specific user that submits the chat. And add CSS to be able to differentiate between the two.

### ISSUE THREAD

**Issue by nakrap** [nakrap/ihaveArrived#19]
Chat submits have to be able to be attributed to who made them. If User 1 says hello, then CSS should align it on the left and be blue in color, and all other messages would be green and aligned on the right. The same goes is User 2 responds. Then message on his screen should show messages on left and User 1 in green on right. However to User 1, when User 2 responds, those messages should be green and to the right.

**Comment by RRaethke** [comment]
I'm on it!
