### ISSUE TITLE
CSS and Bootstrap design of steps when users are created.

### ISSUE THREAD

**Issue by nakrap** [nakrap/ihaveArrived#22]
When Users are created, how will they show up? (Picture, Map, words only?)

Once they are in, how will the buttons look to log the statuses? 

Once the statuses are clicked how will the map look and where will it be placed?

Once the Users meet up, what is going to show up, or happen? 

Once we reset, have everything empty everywhere and start from the beginning again.

**Comment by RRaethke** [comment]
I am working on this in conjunction with the css of the chat. I need to manipulate some of the code for user logins to set specifics on the chat.
